### PR TITLE
Fix removeBackslash message to display backslash correctly

### LINKED ISSUE #2743: Improperly escaped backslash in fix-it message
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
"""
foo \
"""
```

### Description

The following fix-it message contains an improperly escaped backslash.

```swift
extension FixItMessage where Self == StaticParserFixIt {
  ...
  public static var removeBackslash: Self {
    .init("remove '\'")
  }
  ...
}
```

This results in bad diagnostic produced, e.g.

```swift
func testMultilineErrors24() {
  assertParseWithAllNewlineEndings(
    #"""
    _ = """
      foo1️⃣\
      """
    """#,
    diagnostics: [
      DiagnosticSpec(
        message: "escaped newline at the last line of a multi-line string literal is not allowed",
        fixIts: ["remove ''"]
      )
    ],
    fixedSource: #"""
      _ = """
        foo
        """
      """#
  )
}
```

### PR DESCRIPTION
**Pull request by TTOzzi**
Resolve #2743

### CODE REVIEW

File: Tests/SwiftParserTest/translated/MultilineErrorsTests.swift [hunk 1]
```diff
@@ -710,27 +710,6 @@ final class MultilineErrorsTests: ParserTestCase {
...
-          fixIts: ["remove ''"]
-        )
-      ],
-      fixedSource: #"""
-        _ = """
-          foo
-          """
-        """#
-    )
-  }
```
Comment (TTOzzi) [inline Tests/SwiftParserTest/translated/MultilineErrorsTests.swift:731]: Removed it as it was completely redundant with testMultilineErrors24.

**Review by ahoppen — APPROVED** [review]
Thank you!

**Comment by ahoppen** [comment]
@swift-ci Please test
