### PR TITLE
Fix parsing invalid function parameters

### LINKED ISSUE #2254: swift syntax should be able to recover function parameters without argument labels
### Description

SwiftParser currently can’t handle DocC-style abridged signatures such as:

```
init(String.Index, x:(Int) -> Int) rethrows
```

as they are considered malformed parse trees. 

more details at https://forums.swift.org/t/swiftsyntax-how-to-repair-abbreviated-function-signatures/67602

### PR DESCRIPTION
**Pull request by kimdv**
Fixes #2254

### CODE REVIEW

File: Sources/SwiftParser/Parameters.swift [hunk 1]
```diff
@@ -96,11 +96,31 @@ extension Parser {
...
+    var names: ParameterNames
 
+    let unexpectedBeforeColon: RawUnexpectedNodesSyntax?
+    let colon: RawTokenSyntax
     let type: RawTypeSyntax
 
+    // try to parse the type regardless of the presence of the preceding colon
+    // to tackle any unnamed parameter or missing colon
+    // e.g. [X], (:[X]) or (x [X])
+    let canParseType = withLookahead { $0.canParseType() && $0.at(.comma) }
```
Comment (rintaro) [inline Sources/SwiftParser/Parameters.swift:108]: Could you handle `, <type>)` as well? 
```suggestion
    let canParseType = withLookahead { $0.canParseType() && $0.at(.comma, .rightParen) }
```

Comment (kimdv) [reply Sources/SwiftParser/Parameters.swift]: Also added a test case for that. Thanks

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
Thanks. Looks good to me. I think just a few tests need to be updated.

**Comment by kimdv** [comment]
> Thanks. Looks good to me. I think just a few tests need to be updated.

Not sure what is right. 
We have the test case `testInitAccessorsWithDefaultValues`. 

It will change `init(initialValue: <#type#>) {}` -> `init(<#identifier#>: initialValue) {}`. 

I think this is more wrong. 

Would it make sense to assume that if it starts with a lower case, it's an identifier and if it starts with an uppercase it's a type?

**Comment by ahoppen** [comment]
> Would it make sense to assume that if it starts with a lower case, it's an identifier and if it starts with an uppercase it's a type?

I think that’s very reasonable behavior for error recovery. I have wanted to do this in some case in the past but I think that change never made to to a PR.

**Comment by kimdv** [comment]
> > Would it make sense to assume that if it starts with a lower case, it's an identifier and if it starts with an uppercase it's a type?
> 
> I think that’s very reasonable behavior for error recovery. I have wanted to do this in some case in the past but I think that change never made to to a PR.

I was digging a bit into it. 
Where do you think is a propper place, would it be `canParseType()`?

**Comment by ahoppen** [comment]
I would try shoving the uppercase check into the line that currently has.

```swift
 let canParseType = withLookahead { $0.canParseType() && $0.at(.comma, .rightParen) }
```

**Comment by kimdv** [comment]
@swift-ci please test

**Review by ahoppen — APPROVED** [review]
Thanks, Kim. This looks good to me.

**Comment by ahoppen** [comment]
The macOS formatting failure is unrelated. We’re currently working on a fix, should be fixed tomorrow-ish, could you re-trigger CI then?

**Comment by kimdv** [comment]
> The macOS formatting failure is unrelated. We’re currently working on a fix, should be fixed tomorrow-ish, could you re-trigger CI then?

Yes no problem. Will rebase and re-trigger.

**Comment by ahoppen** [comment]
For reference, this is the PR that fixes the format issue: https://github.com/swiftlang/swift/pull/79380

**Comment by kimdv** [comment]
@swift-ci please test
