### PR TITLE
Replace self key path as function usage

### LINKED ISSUE #2796: KeyPath `.self` cannot be resolved in earlier Swift versions
### Description

#2792 introduced a bug in BodyMacroTests.swift:181,

```swift
return body.map(\.self)
```
where `\.self` cannot be resolved by the compiler of some earlier Swift versions.

### Steps to Reproduce

_No response_

### PR DESCRIPTION
**Pull request by mateusrodriguesxyz**
Fixes #2796

I used `map(\.self)` but that's only possible since [Subtyping for keypath literals as functions](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0416-keypath-function-subtyping.md), which landed on Swift 6.0. Thanks @AppAppWorks for catching this.

### CODE REVIEW

File: Tests/SwiftSyntaxMacroExpansionTest/BodyMacroTests.swift [hunk 1]
```diff
@@ -178,7 +178,7 @@ final class BodyMacroTests: XCTestCase {
           } else {
             statements
           }
-        return body.map(\.self)
+        return body.map({ $0.self })
```
Comment (ahoppen) [inline Tests/SwiftSyntaxMacroExpansionTest/BodyMacroTests.swift:181]: Do you think `Array(body)` would convey the intention better than mapping to `self`?

Comment (mateusrodriguesxyz) [reply Tests/SwiftSyntaxMacroExpansionTest/BodyMacroTests.swift:181]: I hadn't thought of that, it's better indeed. I will update it.

**Review by ahoppen — APPROVED** [review]
Thank you!

**Comment by ahoppen** [comment]
@swift-ci Please test
