### PR TITLE
fixed-typed-throws-after-arrow-fixit

### LINKED ISSUE #2391: Fix-its for misplaced typed throws could be improved
### Issue Kind

Bad Diagnostic Produced

### Source Code

```swift
func foo() -> throws(MyError) Int {}
```

### Description

Applying the Fix-It for the parser diagnostics here produces malformed code, because the thrown error type gets lost. The "fixed" code is:

```swift
func foo() throws -> (MyError) Int {}
```

It should be

```swift
func foo() throws(MyError) -> Int {}
```

### PR DESCRIPTION
**Pull request by AppAppWorks**
fixes #2391

### CODE REVIEW

File: Sources/SwiftParser/Parser.swift
Comment (AppAppWorks) [inline Sources/SwiftParser/Parser.swift:1]: I lament I have to resort to this dirty trick to get all tokens marked missing in the`RawTypeSyntax` returned from `parseType`.

File: Sources/SwiftParser/Specifiers.swift [hunk 1]
```diff
@@ -797,20 +798,64 @@ extension Parser {
...
+              }
+
+              virtualParsedOffset = this.currentToken.start
+              return RawThrowsClauseSyntax(
+                throwsSpecifier: synthesizedThrows,
+                leftParen: leftParen,
+                type: type,
+                rightParen: rightParen,
+                arena: this.arena
+              )
```
Comment (AppAppWorks) [inline Sources/SwiftParser/Specifiers.swift:838]: I tried to use a lookahead here to "virtually" parse the throwing type but lookahead methods don't return any `RawSyntax` ;(
I've resorted to rewinding `currentToken` and `lexemes` to emulate virtual parsing which I think is super ugly.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift
Comment (AppAppWorks) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1]: One big issue here is `correctTokens` can no longer be succinctly described by the set of a handful of `TokenSyntax` and `unexpectedTokenCondition` isn't limited to `EffectSpecifier` any more once the throwing type is added to the mix. Is there a good way to validate all tokens of a throwing type?

File: Sources/SwiftParser/Parser.swift
Comment (AppAppWorks) [inline Sources/SwiftParser/Parser.swift:1]: I lament I have to resort to this dirty trick to get all tokens marked missing in theRawTypeSyntax returned from parseType.

Comment (ahoppen) [reply Sources/SwiftParser/Parser.swift:1]: You should be able to re-use the `TokenMissingMaker` we are using here: https://github.com/swiftlang/swift-syntax/blob/70e374101af89aaf998d04587455f0f8d4970751/Sources/SwiftParser/Declarations.swift#L1284-L1293 

If we’re using `TokenMissingMaker`, it would probably make sense to add a method to `Parser` that takes a `RawSyntaxProtocol` and runs `TokenMissingMaker` on it.

File: Sources/SwiftParser/Specifiers.swift [hunk 2]
```diff
@@ -827,4 +872,14 @@ extension Parser {
...
+
+  mutating func virtualParse<T>(block: (inout Self) -> T) -> T {
+    let oldCurrentToken = currentToken
+    let oldLexemes = lexemes
+    defer {
+      currentToken = oldCurrentToken
+      lexemes = oldLexemes
+    }
+    return block(&self)
+  }
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:884]: Why do we need this? If you want to look ahead, you should be able to use a `Lookahead` by calling `lookahead()` on `Parser`. There are a number of places where we do that. 

But really, after parsing a misplaces `throws`, I would just check if the next token is a `(` which is not separated by any trivia from `throws` (ie. trailing trivia of `throws` is empty and leading trivia of `(` is empty). If it is, just continue parsing the thrown type.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift [hunk 3]
```diff
@@ -257,10 +257,16 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
     effectSpecifiers: (some EffectSpecifiersSyntax)?,
     misplacedSpecifiers: UnexpectedNodesSyntax?
   ) {
+    var correctTokens = [effectSpecifiers?.asyncSpecifier, effectSpecifiers?.throwsClause?.throwsSpecifier]
+    if let throwingType = effectSpecifiers?.throwsClause?.type {
+      correctTokens.append(effectSpecifiers?.throwsClause?.leftParen)
+      correctTokens += Array(throwingType.tokens(viewMode: .all))
+      correctTokens.append(effectSpecifiers?.throwsClause?.rightParen)
+    }
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:265]: Couldn’t this be simplified to

```suggestion
    if let throwsClause = effectSpecifiers?.throwsClause {
      correctTokens += throwsClause.tokens(viewMode: .all)
    }
```

File: Sources/SwiftParser/Parser.swift
Comment (AppAppWorks) [reply Sources/SwiftParser/Parser.swift:1]: Which source file would be the best place to house this new method?

File: Sources/SwiftParser/Specifiers.swift [hunk 4]
```diff
@@ -827,4 +861,35 @@ extension Parser {
...
+
+  func withAllTokensMarkedMissing<T: RawSyntaxNodeProtocol>(source: T) -> T {
+    let tokenMissingMaker = TokenMissingMaker(arena: self.arena)
+    let allMissing = tokenMissingMaker.rewrite(
+      Syntax(raw: RawSyntax(source), rawNodeArena: self.arena)
+    ).raw
+    return allMissing.cast(T.self)
+  }
+}
```
Comment (AppAppWorks) [inline Sources/SwiftParser/Specifiers.swift:879]: I tentatively placed the code here, not knowing the ideal source file to house it.

File: Tests/SwiftParserTest/DeclarationTests.swift [hunk 5]
```diff
@@ -951,6 +951,41 @@ final class DeclarationTests: ParserTestCase {
...
+    assertParse(
+      "func test() -> 1️⃣throws /* comment */ (any Error) Int",
+      diagnostics: [
+        DiagnosticSpec(
+          message: "'throws /* comment */ (any Error)' must precede '->'",
+          fixIts: ["move 'throws /* comment */ (any Error)' in front of '->'"]
+        )
+      ],
+      fixedSource: "func test() throws(any Error) -> /* comment */  Int"
+    )
```
Comment (AppAppWorks) [inline Tests/SwiftParserTest/DeclarationTests.swift:986]: @ahoppen, you've mentioned we should only continue parsing the type if there are no whitespace and comment trivia between `throws` and `.leftParen`. Here I noticed that the comment trivia is left in place in the fixed source after applying the fix-it even though `/* comment */` is included in the message and fix-it. Is it because of the issue of `parsedToken` vs `materializedToken`?

However, `throws /* comment */ (any Error)` is also a legit throws clause, shouldn't it be supported by this fix-it?

File: Sources/SwiftParser/Specifiers.swift (hunk 4 above)
Comment (ahoppen) [reply Sources/SwiftParser/Specifiers.swift:879]: How about placing it in Parser.swift, making `TokenMissingMaker` `private` and also using `withAllTokensMarkedMissing` in [Declarations.swift](https://github.com/swiftlang/swift-syntax/blob/70e374101af89aaf998d04587455f0f8d4970751/Sources/SwiftParser/Declarations.swift#L1284-L1293)?

File: Sources/SwiftParser/Specifiers.swift [hunk 6]
```diff
@@ -797,20 +798,53 @@ extension Parser {
...
+                throwsSpecifier: synthesizedThrows,
+                leftParen: nil,
+                type: nil,
+                rightParen: nil,
+                arena: self.arena
+              )
+              break
+            }
+
+            let leftParen = self.consume(if: .leftParen)!
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:816]: Let’s make this `self.expect`. That way we avoid the force unwrap.

```suggestion
            let leftParen = self.expect(.leftParen)
```

And for symmetry, I would also use `expect` to get the right parenthesis.

File: Sources/SwiftParser/Specifiers.swift [hunk 7]
```diff
@@ -797,20 +798,53 @@ extension Parser {
...
+            synthesizedThrowsClause = RawThrowsClauseSyntax(
+              throwsSpecifier: synthesizedThrows,
+              leftParen: missingToken(.leftParen),
+              type: self.withAllTokensMarkedMissing(source: type),
+              rightParen: rightParen != nil ? missingToken(.rightParen) : nil,
+              arena: self.arena
+            )
+
+            unexpected.append(leftParen)
+            unexpected += type.allTokens
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:829]: You should be able to shove the entire `type` into `unexpected` if you make it a `[RawSyntax]` instead of `[RawTokenSyntax]`. You can also remove the `allTokens` property then.

File: Tests/SwiftParserTest/DeclarationTests.swift (hunk 5 above)
Comment (ahoppen) [reply Tests/SwiftParserTest/DeclarationTests.swift:986]: Sorry, I should have elaborate when I suggested the no spacing rule: If a user writes `func foo() -> throws (Int, Int)`, the `(Int, Int)` very likely isn’t the thrown error type but the return type and I want to avoid generating a Fix-It that moves `throws (Int, Int)` in front of the arrow.

And if a user has a space between `throws` and the thrown error type and also writes the clause after the arrow, I am fine with producing a sub-optimal diagnostic because those two choices/mistakes combined are quite unlikely. 

---

And also congrats for noticing the `throws /* comment */ (any Error)` case. Shows a great attention to detail 🤩

File: Sources/SwiftParser/Specifiers.swift (hunk 6 above)
Comment (AppAppWorks) [reply Sources/SwiftParser/Specifiers.swift:816]: In my current design, a thrown type missing the right parenthesis is allowed to recover, do you think such recovery should be disallowed?

Comment (ahoppen) [reply Sources/SwiftParser/Specifiers.swift]: It should be able to recover with `self.expect` as well. The only difference is whether `rightParen` is set to `nil` or a missing right parenthesis.

File: Sources/SwiftParser/Specifiers.swift [hunk 8]
```diff
@@ -795,22 +796,56 @@ extension Parser {
...
-            synthesizedThrows = missingToken(spec)
-          } else {
-            synthesizedThrows = missingToken(.throws)
+        guard effectSpecifiers?.throwsClause == nil else {
+          continue
+        }
+        if matchedSubset == S.CorrectThrowsTokenKinds.self {
+          let synthesizedThrows = missingToken(spec)
+          var lookahead = self.lookahead()
+          guard lookahead.consume(if: .leftParen) != nil,
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:805]: Could you add a check for whether the is a space between `throws` and the left parenthesis, similar to here

https://github.com/swiftlang/swift-syntax/blob/93df9ed82e07760eb8eceb09a4504d7057110da3/Sources/SwiftParser/Attributes.swift#L184

A test case for this would be that `func foo() -> throws (Int, Int)` has a Fix-It to move the `throws` but not `(Int, Int)`.

File: Sources/SwiftParser/Specifiers.swift [hunk 9]
```diff
@@ -795,22 +796,56 @@ extension Parser {
...
+              throwsSpecifier: synthesizedThrows,
+              leftParen: nil,
+              type: nil,
+              rightParen: nil,
+              arena: self.arena
+            )
+            continue
           }
+
+          let leftParen = self.expect(.leftParen).token
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:818]: We shouldn’t be discarding the unexpected tokens from `expect`. I know that it can’t really happen here because we check in `lookahead.consume(if:)` that the next token is a left parenthesis but in general, dropping syntax nodes can lead to a syntax tree that doesn’t represent the original source code and it’s good practice to never drop anything. I’d change this to

```swift
let (unexpectedBeforeLeftParen, leftParen) = self.expect(.leftParen)
```
change `unexpected` to be of type `[RawSyntax]` (which requires a few conversions from `RawTokenSyntax` to `RawSyntax` using the `RawSyntax` initializer) and then below do

```swift
if let unexpectedBeforeLeftParen {
  unexpected.append(RawSyntax(unexpectedBeforeLeftParen))
}
unexpected.append(RawSyntax(leftParen))
unexpected.append(RawSyntax(type))
```

Notice how you also don’t need `allTokens` on `type` anymore.

And then you could do the same for `rightParen` to also use `expect`.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift
Comment (ahoppen) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1]: Ah, I see. That’s why you have to use `allTokens` during parsing. 

It think we need to have a generalized version of `exchangeTokens` that works on general `Syntax` nodes instead of `TokenSyntax`.

Comment (AppAppWorks) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1]: Should I try to generalise `exchangeTokens` in this PR, or just raise another issue?

Comment (ahoppen) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:1]: If you could generalize it in this PR, that would be great

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift [hunk 10]
```diff
@@ -171,6 +171,46 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
...
+  /// into `misplacedTokens`.  All tokens in `correctNodes` will be flattened into `correctTokens`.  After that the
+  /// remaining operations will be the same as `exchangeTokens`.
+  public func exchangeNodes(
+    unexpected: UnexpectedNodesSyntax?,
+    unexpectedNodeCondition: (Syntax) -> Bool,
+    correctNodes: [Syntax?],
+    message: (_ misplacedTokens: [TokenSyntax]) -> some DiagnosticMessage,
+    moveFixIt: (_ misplacedTokens: [TokenSyntax]) -> FixItMessage,
+    removeRedundantFixIt: (_ misplacedTokens: [TokenSyntax]) -> FixItMessage? = { _ in nil }
+  ) {
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:187]: Instead of implementing `exchangeNodes` in terms of `exchangeTokens`, would it be possible to just generalize `exchangeTokens` to work `Syntax` instead of `TokenSyntax`? I briefly looked through it and I didn’t find any huge blockers but I might have missed something.

File: Sources/SwiftParser/Specifiers.swift [hunk 11]
```diff
@@ -772,16 +772,21 @@ extension Parser {
...
-    var synthesizedThrows: RawTokenSyntax? = nil
-    var unexpected: [RawTokenSyntax] = []
+    var synthesizedThrowsClause: RawThrowsClauseSyntax? = nil
+    var unexpected: [RawSyntax] = []
     var loopProgress = LoopProgressCondition()
+
+    func unexpect(_ node: some RawSyntaxNodeProtocol) {
+      unexpected.append(RawSyntax(node))
+    }
+
```
Comment (ahoppen) [inline Sources/SwiftParser/Specifiers.swift:782]: I personally think that the code is more readable if you just inline this code. Then it’s easier to follow where `unexpected` is being built up, IMO.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift [hunk 12]
```diff
@@ -171,26 +171,38 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
...
     moveFixIt: (_ misplacedTokens: [TokenSyntax]) -> FixItMessage,
     removeRedundantFixIt: (_ misplacedTokens: [TokenSyntax]) -> FixItMessage? = { _ in nil }
   ) {
     guard let incorrectContainer = unexpected else { return }
-    let misplacedTokens = incorrectContainer.presentTokens(satisfying: unexpectedTokenCondition)
-    if misplacedTokens.isEmpty { return }
+    let misplacedNodes = incorrectContainer.compactMap { $0.as(S.self) }.filter(unexpectedNodeCondition)
+    let misplacedTokens = misplacedNodes.flatMap {
+      Array($0.tokens(viewMode: .sourceAccurate))
+    }
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:193]: Couldn’t this just be `[Syntax]` as well? `FixIt.MultiNodeChange.makeMissing` supports nodes as well as tokens and I assume that `message`, `moveFixIt`, and `removeRedundantFixIt` could be changed to take `[Syntax]`. And `misplacedTokens.only` could become `misplacedTokens.only.as(TokenSyntax.self)`.

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift [hunk 13]
```diff
@@ -171,26 +171,38 @@ public class ParseDiagnosticsGenerator: SyntaxAnyVisitor {
...
+    guard !misplacedTokens.isEmpty else { return }
 
-    let correctTokens = correctTokens.compactMap({ $0 })
+    let correctTokens = correctNodes.flatMap { node -> [TokenSyntax] in
+      if let node {
+        Array(node.tokens(viewMode: .all))
+      } else {
+        []
+      }
+    }
```
Comment (ahoppen) [inline Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:202]: I think this could also be `[Syntax]`:
- `correctTokens.only` would just need to become `correctTokens.only.as(TokenSyntax.self)`
- `correctTokens.filter(\.isMissing)` could become `correctTokens.filter(\.isMissingAllTokens)`

File: Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift (hunk 12 above)
Comment (ahoppen) [reply Sources/SwiftParserDiagnostics/ParseDiagnosticsGenerator.swift:193]: Ah, that’s unfortunate. I was hoping that the changes to the `message` etc. closures would be minimal. I still think it would be good to migrate them to `Syntax` but that doesn’t need to be part of this PR. Could you file an issue for that so we can do the migration later?

**Comment by AppAppWorks** [comment]
@ahoppen, could you review my latest commit? :)

**Comment by ahoppen** [comment]
Did you try to address https://github.com/swiftlang/swift-syntax/pull/2731#discussion_r1688770662?

**Comment by AppAppWorks** [comment]
> Did you try to address [#2731 (comment)](https://github.com/swiftlang/swift-syntax/pull/2731#discussion_r1688770662)?

I might have tried that but now I've forgotten it ;)  
I'll have a quick check and come back to you!

**Comment by AppAppWorks** [comment]
[#2731 (comment)](https://github.com/swiftlang/swift-syntax/pull/2731#discussion_r1688770662) addressed.

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by AppAppWorks** [comment]
Fixed, please test again.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
