### PR TITLE
Fix Accessor Macros Attached to Properties With Trailing Comments

### LINKED ISSUE #2614: Accessor Macros applied to properties with trailing trivia comments lead to Swift that fails to compile.
### Description

The following Swift code fails to compile:

```swift
var x: Int // comment {
  get {
    return 1
  }
}
```

The trailing trivia comment captures the opening round brace… which leads to the compiler error.

We can attach an accessor macro to a variable declaration with similar trailing trivia:

```swift
@constantOne
var x: Int // comment
```

Which expands to:

```swift
var x: Int // comment {
  get {
    return 1
  }
}
```

Maybe we should do something about that comment trivia… could we place the comment trivia after (to the right of) the opening curly brace?

```swift
var x: Int { // comment
  get {
    return 1
  }
}
```

Could we enclose the trailing trivia with asterisks?

```swift
var x: Int /* comment */ {
  get {
    return 1
  }
}
```

### Steps to Reproduce

Here is a diff on `swift-syntax` to repro:

```
diff --git a/Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift b/Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift
index 471a34c7..97e2b8bc 100644
--- a/Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift
+++ b/Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift
@@ -43,6 +43,24 @@ fileprivate struct ConstantOneGetter: AccessorMacro {
 
 final class AccessorMacroTests: XCTestCase {
   private let indentationWidth: Trivia = .spaces(2)
+  
+  func testAccessorWithComment() {
+    assertMacroExpansion(
+      """
+      @constantOne
+      var x: Int // comment
+      """,
+      expandedSource: """
+        var x: Int {
+          get {
+            return 1
+          }
+        }
+        """,
+      macros: ["constantOne": ConstantOneGetter.self],
+      indentationWidth: indentationWidth
+    )
+  }
 
   func testAccessorOnVariableDeclWithExistingGetter() {
     assertMacroExpansion(

```

### PR DESCRIPTION
**Pull request by AppAppWorks**
Fixed #2614

### CODE REVIEW

File: Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift [hunk 1]
```diff
@@ -44,6 +44,95 @@ fileprivate struct ConstantOneGetter: AccessorMacro {
...
+      expandedSource: """
+        var x: Int { // hello
+        get {
+            1
+        }
+          get {
+            return 1
+          }
+        }
+        """,
```
Comment (AppAppWorks) [inline Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift:130]: I discovered that adding a trailing comment to the left brace of the accessor block will mess up the indentation levels of the generated getter.

**Comment by AppAppWorks** [comment]
@bnbarham could you review this PR if @ahoppen isn't available?

File: Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift [hunk 2]
```diff
@@ -44,6 +44,95 @@ fileprivate struct ConstantOneGetter: AccessorMacro {
...
   private let indentationWidth: Trivia = .spaces(2)
 
+  func testAccessorOnVariableDeclWithTrailingLineCommentAndNoAccessorBlock() {
+    assertMacroExpansion(
+      """
+      @constantOne
+      var x: Int // hello
+      """,
+      expandedSource: """
+        var x: Int /* hello*/ {
```
[the remark this answers is not in the document]
Comment (AppAppWorks) [reply Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift:54]: I was bikeshedding between keeping the style intact or converting them into block, I picked the conversion route because it was slightly easier to code ;)

I agree source fidelity is important, I'll make some changes in the next commit.

[the remark this answers is not in the document]
Comment (AppAppWorks) [reply Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift]: @bnbarham, please have a look at my latest commit.

File: Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift [hunk 3]
```diff
@@ -44,6 +44,95 @@ fileprivate struct ConstantOneGetter: AccessorMacro {
...
   private let indentationWidth: Trivia = .spaces(2)
 
+  func testAccessorOnVariableDeclWithTrailingLineCommentAndNoAccessorBlock() {
+    assertMacroExpansion(
+      """
+      @constantOne
+      var x: Int /*1*/ // hello
+      """,
+      expandedSource: """
+        var x: Int /*1*/  {// hello
```
Comment (bnbarham) [inline Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift:54]: I wouldn't worry so much about only moving `//`/`///` style comments and instead just move all of the trailing trivia. That would also help with fixing the double space here (and we can just make sure to insert a space between `Int` and `{`.

Comment (AppAppWorks) [reply Tests/SwiftSyntaxMacroExpansionTest/AccessorMacroTests.swift]: Thanks, I've made changes accordingly, please have a look.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 4]
```diff
@@ -923,24 +923,34 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
       contextGenerator(Syntax(node)).addDiagnostics(
         from: MacroApplicationError.accessorMacroOnVariableWithMultipleBindings,
         node: node
       )
       return DeclSyntax(node)
     }
-
-    let expansion = expandAccessors(of: node, existingAccessors: binding.accessorBlock)
+    
+    let bindingKeyPath = \VariableDeclSyntax.bindings[node.bindings.startIndex]
```
Comment (bnbarham) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:934]: I mildly prefer just keeping `node.bindings[node.bindings.startIndex]` TBH. Maybe we should have a `mutate` method or something similar to make this a little nicer, or just wait until we can use variadic generics and then update `with`...

**Review by bnbarham — APPROVED** [review]
Thanks @AppAppWorks!

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by AppAppWorks** [comment]
I've run swift-format, please test again.

**Comment by bnbarham** [comment]
@swift-ci please test

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift (hunk 4 above)
Comment (ahoppen) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:934]: I agree that the bindings key path is a little confusing, it just seems a little over-complicated

What do you think about having `var binding = node.bindings.first` in the `guard`, then using `binding.accessorBlock = …` etc below and finalizing the new node by setting `node.bindings = [binding]`. That seems like the cleanest solution to me.

File: Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift [hunk 5]
```diff
@@ -923,24 +923,34 @@ private class MacroApplication<Context: MacroExpansionContext>: SyntaxRewriter {
...
+    let binding = node[keyPath: bindingKeyPath]
+    var expansion = expandAccessors(of: node, existingAccessors: binding.accessorBlock)
+
     if expansion.accessors != binding.accessorBlock {
+      if binding.accessorBlock == nil {
+        // remove the trailing trivia of the variable declaration and move it
+        // to the trailing trivia of the left brace of the newly created accessor block
+        node[keyPath: bindingKeyPath].trailingTrivia = []
+        expansion.accessors?.leftBrace.trailingTrivia = binding.trailingTrivia
+      }
```
Comment (ahoppen) [inline Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:944]: This would still be an issue if the macro expands to an accessor that doesn’t have a newline after the `{`, right? Ie. you have a macro that expands to `{ 1 }` and has formatting disabled, so no newline gets added by `BasicFormat`.

If that’s the case, I would just move the trailing trivia after the closing brace. That way you can conceptually think of the accessor as being inserted before the binding’s trailing trivia.

Comment (AppAppWorks) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:944]: How could I disable formatting for a test case?

Comment (bnbarham) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:944]: You'll need to add a new macro and then set `static let formatMode: FormatMode = .disabled` in its definition. Also, nice catch @ahoppen! I forgot about that case :)

Comment (AppAppWorks) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:944]: I couldn't figure out how to make an `AccessorMacro` expand into something like `{ 1 }`, how could I do this?

Comment (ahoppen) [reply Sources/SwiftSyntaxMacroExpansion/MacroSystem.swift:944]: The following should test it

```swift
func testAccessorOnVariableDeclWithTrailingLineCommentAndAccessorBlock2() {
  struct ConstantOneSingleLineGetter: AccessorMacro {
    static var formatMode: FormatMode { .disabled }

    static func expansion(
      of node: AttributeSyntax,
      providingAccessorsOf declaration: some DeclSyntaxProtocol,
      in context: some MacroExpansionContext
    ) throws -> [AccessorDeclSyntax] {
      return [
        """
        get { 1 }
        """
      ]
    }
  }

  assertMacroExpansion(
    """
    @constantOne
    var x: Int // hello
    """,
    expandedSource: """
      var x: Int { // hello
        get { 1 }
      }
      """,
    macros: ["constantOne": ConstantOneSingleLineGetter.self],
    indentationWidth: indentationWidth
  )
}
```

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@AppAppWorks Could you add the test case I suggested in https://github.com/swiftlang/swift-syntax/pull/2722#discussion_r1681564244?

**Comment by AppAppWorks** [comment]
> @AppAppWorks Could you add the test case I suggested in [#2722 (comment)](https://github.com/swiftlang/swift-syntax/pull/2722#discussion_r1681564244)?

Done, please have a look.

**Review by ahoppen — APPROVED** [review]

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by AppAppWorks** [comment]
Could you test Windows too? :)

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform
